import Head from "next/head";
import Layout from "@/components/Layout";
import Header from "@/components/Header";
import TodosForTodayCard from "@/components/TodosForTodayCard";
import { getTodos } from "@/lib/notion";
import { Todo } from "@/types/types";
import Card from "@/components/Card";
import { Chip } from "@mui/material";

export default function Home(todos: { todos: Todo[] }) {
	const allTodos = todos.todos.map((todo) => todo);
	const today = new Date();

	return (
		<Layout>
			<Head>
				<title>Daily Life</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<Header title={"Dzień dobry, Oliwka!"}/>

			{/*<TodosForTodayCard todos={allTodos}/>*/}

			<Card>
				<h3>Todos na dziś</h3>
				<div>
					{
						allTodos.filter(todo => new Date(todo.date).toDateString() === today.toDateString())
							 .map(todo =>
								 (
									 <div>
										 <Chip
											 variant="filled"
											 size="small"
											 label={todo.status}
										 />
										 {todo.title}
									 </div>
								 )
							 )
					}
				</div>
			</Card>
		</Layout>
	);
}

export const getStaticProps = async () => {
	const data = await getTodos();

	return {
		props: {
			todos: data
		},
		revalidate: 60
	};
};